# Generated by Django 3.1.2 on 2021-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('linkActor', models.TextField(verbose_name='Link actor')),
                ('fechaNacimiento', models.TextField(verbose_name='Fecha de nacimiento')),
                ('lugarNacimiento', models.TextField(verbose_name='Lugar de nacimiento')),
                ('foto', models.ImageField(upload_to='', verbose_name='Foto')),
                ('biografia', models.TextField(verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Personal')),
                ('puesto', models.TextField(default='productor', verbose_name='Puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(unique=True, verbose_name='Titulo')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('duracion', models.TextField(verbose_name='Duracion')),
                ('linkPelicula', models.TextField(verbose_name='Link de la pelicula')),
                ('portada', models.ImageField(upload_to='', verbose_name='Portada')),
                ('actores', models.ManyToManyField(to='main.Actor')),
                ('generos', models.ManyToManyField(to='main.Genero')),
                ('personal', models.ManyToManyField(to='main.Personal')),
            ],
        ),
    ]
